spring.application.name=KisanUnnatiBackend
# ===============================
# Database Configuration
# ===============================
# ===============================
# Primary Database (kisanunnati)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/kisanunnati
spring.datasource.username=root
spring.datasource.password=Mdjaved2004

# ===============================
# Hibernate / JPA Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# View Resolver Configuration (Spring MVC)
# ===============================
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp